version: '2'

services:
  mdb:
    image: mongo:3.4.3
    ports:
      - "27017"
    command: mongod --replSet=bigchain-rs

  bdb:
    image: bigchaindb/bigchaindb
    environment:
      BIGCHAINDB_DATABASE_BACKEND: mongodb
      BIGCHAINDB_DATABASE_HOST: mdb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_WSSERVER_PORT: 9985
      BIGCHAINDB_KEYPAIR_PUBLIC: GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4
      BIGCHAINDB_KEYPAIR_PRIVATE: 2kQgBtQnHoauw8QchKM7xYvEBW1QDoHzhBsCL9Vi1AzB
    ports:
      - "9984:9984"
      - "9985:9985"
    command: start

  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    environment:
      REACT_APP_BDB_SERVER_URL: "http://localhost:9984"
      REACT_APP_BDB_WS_URL: "ws://localhost:9985"
    ports:
      - "3000:3000"
    command: npm start
